### ISSUE TITLE
TODO: The needed stuff for 0.0.1. This pr will be updated with changes and todo things

### ISSUE THREAD

**Issue by Scraayp** [Scraayp/Hez#1]
# Add:

### Commands

- [ ] ping
- [ ] userinfo

### Utils 

- [ ] Database
- [ ] Error loggings with db entry
- [ ] Message counter

### Events

- [ ] On ready
- [ ] Message delete/edit
- [ ] On ban db entry

# Bugs:

**Comment by Scraayp** [comment]
This has been changed into cards of projects
